# Generated by Django 6.0.2 on 2026-02-13 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(help_text='3-30 character username (letters, digits, underscores).', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-30 characters (letters, digits, underscores).', regex='^[a-zA-Z0-9_]{3,30}$')]),
        ),
    ]
