import { motion } from "framer-motion";
import {
  CheckCircle, XCircle, AlertTriangle,
  Brain, Download, Share2, RefreshCw,
  AlertOctagon, ChevronRight, Info, Shield, Globe
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { AnalysisResult } from "@/hooks/useNewsAnalysis";

type FullReportSectionProps = {
  result: AnalysisResult;
  query: string;
  onClear: () => void;
  onRerun?: () => void;
};

const verdictConfig = {
  real: {
    icon: CheckCircle,
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-50 dark:bg-emerald-950/50",
    borderColor: "border-emerald-200 dark:border-emerald-800",
    badgeBg: "bg-emerald-100 dark:bg-emerald-900 text-emerald-700 dark:text-emerald-300",
    label: "Credible",
  },
  fake: {
    icon: XCircle,
    color: "text-red-600 dark:text-red-400",
    bgColor: "bg-red-50 dark:bg-red-950/50",
    borderColor: "border-red-200 dark:border-red-800",
    badgeBg: "bg-red-100 dark:bg-red-900 text-red-700 dark:text-red-300",
    label: "Fake",
  },
  misleading: {
    icon: AlertTriangle,
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-50 dark:bg-amber-950/50",
    borderColor: "border-amber-200 dark:border-amber-800",
    badgeBg: "bg-amber-100 dark:bg-amber-900 text-amber-700 dark:text-amber-300",
    label: "Potentially Misleading",
  },
};

const getScoreColor = (score: number) => {
  if (score >= 70) return "text-emerald-600 dark:text-emerald-400";
  if (score >= 50) return "text-slate-600 dark:text-slate-400";
  if (score > 30) return "text-amber-600 dark:text-amber-400";
  return "text-red-600 dark:text-red-400";
};

const getScoreBarColor = (score: number) => {
  if (score >= 70) return "bg-emerald-500";
  if (score >= 50) return "bg-slate-400";
  if (score > 30) return "bg-amber-500";
  return "bg-red-500";
};

const getSourceStatusLabel = (status: string, note: string) => {
  const lowerNote = note.toLowerCase();

  if (status === "matched") {
    if (lowerNote.includes("trusted source domain")) {
      return "matched (submitted URL belongs to trusted source domain)";
    }
    return "matched";
  }

  if (status === "contradicted") return "contradicted";
  if (status === "partial") return "partial";
  return "not matched";
};

const getSourceSecondaryNote = (sourceName: string, status: string, note: string) => {
  const trimmedNote = note.trim();
  if (!trimmedNote) return "";

  const lowerNote = trimmedNote.toLowerCase();
  const lowerSourceName = sourceName.trim().toLowerCase();
  const statusLabel = getSourceStatusLabel(status, trimmedNote).toLowerCase();
  const compactNote = lowerNote.replace(/[.:]/g, "").trim();
  const compactStatus = statusLabel.replace(/[.:]/g, "").trim();
  const compactSource = lowerSourceName.replace(/[.:]/g, "").trim();

  if (compactNote === compactStatus) return "";
  if (compactSource && compactNote === `${compactSource} ${compactStatus}`) return "";
  if (compactSource && compactNote === `${compactSource} - ${compactStatus}`) return "";
  if (compactSource && compactNote === `${compactSource} — ${compactStatus}`) return "";
  if (compactNote.startsWith(`${statusLabel} `)) return "";
  if (compactSource && compactNote.startsWith(`${compactSource} `)) {
    if (compactNote.includes("not matched") || compactNote.includes("matched")) return "";
  }
  if (compactNote.startsWith("matched") || compactNote.startsWith("not matched")) return "";

  return trimmedNote;
};

const FullReportSection = ({ result, query, onClear, onRerun }: FullReportSectionProps) => {
  const config = verdictConfig[result.verdict];
  const VerdictIcon = config.icon;
  const ai = result.explainableAI;
  const explanationFallback = result.llmStatus === "error"
    ? `AI explanation unavailable: ${result.llmError || "LLM processing failed."}`
    : "AI explanation not available.";

  const handleDownload = () => {
    const aiSection = ai
      ? `
Summary:
${ai.summary}

Reasoning:
${ai.reasoning.map((r, i) => `${i + 1}. ${r}`).join("\n")}

Inconsistencies:
${ai.inconsistencies.length > 0 ? ai.inconsistencies.map((r, i) => `${i + 1}. ${r}`).join("\n") : "None found."}

Recommendations:
${ai.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}`
      : `\n${explanationFallback}`;

    const reportText = `TruthLens Verification Report
=============================
Query: ${query}
Verdict: ${config.label}
Credibility Score: ${result.credibilityScore}/100
${aiSection}

Generated by TruthLens AI Fact Checker`.trim();

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "truthlens-report.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    const shareText = `TruthLens Report: ${config.label} (${result.credibilityScore}/100) - ${query.substring(0, 100)}...`;
    if (navigator.share) {
      await navigator.share({ title: "TruthLens Report", text: shareText });
    } else {
      await navigator.clipboard.writeText(shareText);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="w-full max-w-3xl mx-auto space-y-6"
    >
      {/* ── Verdict & Credibility Score ───────────────────────────── */}
      <Card className={`${config.bgColor} ${config.borderColor} border-2 shadow-xl`}>
        <CardContent className="p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
            <div className="flex items-center gap-4">
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ type: "spring", stiffness: 300, delay: 0.2 }}
                className={`w-14 h-14 rounded-2xl ${config.bgColor} border-2 ${config.borderColor} flex items-center justify-center flex-shrink-0`}
              >
                <VerdictIcon className={`w-8 h-8 ${config.color}`} />
              </motion.div>
              <div>
                <h2 className={`font-display text-2xl lg:text-3xl font-bold ${config.color}`}>
                  {config.label}
                </h2>
              </div>
            </div>

            {/* Action buttons */}
            <div className="flex flex-wrap gap-2">
              <Button variant="outline" size="sm" onClick={handleDownload} className="gap-2 text-slate-700 dark:text-slate-200 border-slate-300 dark:border-slate-600 hover:bg-slate-100 dark:hover:bg-slate-700">
                <Download className="w-4 h-4" />
                Download
              </Button>
              <Button variant="outline" size="sm" onClick={handleShare} className="gap-2 text-slate-700 dark:text-slate-200 border-slate-300 dark:border-slate-600 hover:bg-slate-100 dark:hover:bg-slate-700">
                <Share2 className="w-4 h-4" />
                Share
              </Button>
              {onRerun && (
                <Button variant="ghost" size="sm" onClick={onRerun} className="gap-2 text-slate-600 dark:text-slate-300">
                  <RefreshCw className="w-4 h-4" />
                  Re-run
                </Button>
              )}
            </div>
          </div>

          {/* Credibility Score */}
          <div className="p-4 rounded-xl bg-white/80 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium text-slate-600 dark:text-slate-400">
                Credibility Score
              </span>
              <span className={`text-3xl font-bold font-display ${getScoreColor(result.credibilityScore)}`}>
                {result.credibilityScore}<span className="text-lg text-slate-400 dark:text-slate-500">/100</span>
              </span>
            </div>
            <div className="h-2.5 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${result.credibilityScore}%` }}
                transition={{ duration: 0.8, delay: 0.3, ease: "easeOut" }}
                className={`h-full rounded-full ${getScoreBarColor(result.credibilityScore)}`}
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* ── Source Verification ─────────────────────────────────── */}
      {result.sourceVerificationData && result.sourceVerificationData.verificationEnabled && (
        <Card className="shadow-lg border-slate-200 dark:border-slate-700">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-slate-900 dark:text-slate-100">
              <Shield className="w-5 h-5 text-secondary" />
              Source Verification
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {/* Status & Count */}
              <div className="flex flex-wrap gap-3">
                <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-medium ${
                  result.sourceVerificationData.verificationStatus === "supported"
                    ? "bg-emerald-100 dark:bg-emerald-900/50 text-emerald-700 dark:text-emerald-300"
                    : result.sourceVerificationData.verificationStatus === "partially_supported"
                      ? "bg-amber-100 dark:bg-amber-900/50 text-amber-700 dark:text-amber-300"
                      : "bg-red-100 dark:bg-red-900/50 text-red-700 dark:text-red-300"
                }`}>
                  {result.sourceVerificationData.verificationStatus === "supported" ? (
                    <CheckCircle className="w-4 h-4" />
                  ) : result.sourceVerificationData.verificationStatus === "partially_supported" ? (
                    <AlertTriangle className="w-4 h-4" />
                  ) : (
                    <XCircle className="w-4 h-4" />
                  )}
                  {result.sourceVerificationData.verificationStatus === "supported"
                    ? "Supported"
                    : result.sourceVerificationData.verificationStatus === "partially_supported"
                      ? "Partially Supported"
                      : "Unsupported"}
                </div>
                <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-slate-100 dark:bg-slate-800 text-sm text-slate-600 dark:text-slate-400">
                  <Globe className="w-4 h-4" />
                  {result.sourceVerificationData.sourceCount} source{result.sourceVerificationData.sourceCount !== 1 ? "s" : ""} matched
                </div>
              </div>

              {/* Source status by trusted outlet */}
              {result.sourceVerificationData.perSourceStatuses.length > 0 && (
                <div className="space-y-2">
                  {result.sourceVerificationData.perSourceStatuses.map((src, idx) => (
                    <div
                      key={idx}
                      className="flex items-center gap-3 p-3 rounded-lg bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700"
                    >
                      <div className="w-8 h-8 rounded-full bg-secondary/20 flex items-center justify-center flex-shrink-0">
                        <Globe className="w-4 h-4 text-secondary" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="font-medium text-slate-800 dark:text-slate-200">
                            {src.sourceName}
                          </span>
                          <span className="text-xs text-slate-500 dark:text-slate-400">
                            {getSourceStatusLabel(src.status, src.note)}
                          </span>
                        </div>
                        {getSourceSecondaryNote(src.sourceName, src.status, src.note) && (
                          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                            {getSourceSecondaryNote(src.sourceName, src.status, src.note)}
                          </p>
                        )}
                      </div>
                      {src.status === "matched" ? (
                        <CheckCircle className="w-4 h-4 text-emerald-500 flex-shrink-0" />
                      ) : src.status === "contradicted" ? (
                        <XCircle className="w-4 h-4 text-red-500 flex-shrink-0" />
                      ) : (
                        <AlertTriangle className="w-4 h-4 text-amber-500 flex-shrink-0" />
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── AI Explanation ────────────────────────────────────────── */}
      <Card className="shadow-lg border-slate-200 dark:border-slate-700">
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-slate-900 dark:text-slate-100">
            <Brain className="w-5 h-5 text-secondary" />
            AI Explanation
          </CardTitle>
        </CardHeader>
        <CardContent>
          {ai ? (
            <div className="space-y-6">
              {/* Summary */}
              <div>
                <h4 className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-2">
                  Summary
                </h4>
                <p className="text-slate-800 dark:text-slate-200 leading-relaxed text-base">
                  {ai.summary}
                </p>
              </div>

              {/* Reasoning */}
              {ai.reasoning.length > 0 && (
                <div>
                  <h4 className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-2">
                    Reasoning
                  </h4>
                  <ul className="space-y-2">
                    {ai.reasoning.map((point, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-slate-700 dark:text-slate-300 leading-relaxed">
                        <ChevronRight className="w-4 h-4 mt-1 text-secondary flex-shrink-0" />
                        {point}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Inconsistencies */}
              <div>
                <h4 className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-2">
                  Inconsistencies
                </h4>
                {ai.inconsistencies.length > 0 ? (
                  <ul className="space-y-2">
                    {ai.inconsistencies.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-slate-700 dark:text-slate-300 leading-relaxed">
                        <AlertOctagon className="w-4 h-4 mt-1 text-amber-500 flex-shrink-0" />
                        {item}
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="text-slate-500 dark:text-slate-400 italic">
                    No inconsistencies found.
                  </p>
                )}
              </div>

              {/* Recommendations */}
              {ai.recommendations.length > 0 && (
                <div>
                  <h4 className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-2">
                    Recommendations
                  </h4>
                  <ul className="space-y-2">
                    {ai.recommendations.map((rec, idx) => (
                      <li key={idx} className="flex items-start gap-3 p-3 rounded-lg bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                        <span className="flex-shrink-0 w-6 h-6 rounded-full bg-secondary/20 flex items-center justify-center text-xs font-bold text-secondary">
                          {idx + 1}
                        </span>
                        <span className="text-slate-700 dark:text-slate-300 leading-relaxed">{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          ) : (
            /* Fallback when explainable_ai is missing */
            <div className="flex items-center gap-3 p-5 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
              <Info className="w-5 h-5 text-slate-400 flex-shrink-0" />
              <p className="text-slate-500 dark:text-slate-400">
                {explanationFallback}
              </p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* ── Bottom Actions ────────────────────────────────────────── */}
      <div className="flex justify-center gap-4 pt-4 pb-8">
        <Button variant="outline" size="lg" onClick={onClear} className="gap-2 text-slate-700 dark:text-slate-200 border-slate-300 dark:border-slate-600">
          <RefreshCw className="w-5 h-5" />
          Check Another Content
        </Button>
      </div>
    </motion.div>
  );
};

export default FullReportSection;
