# Generated by Django 6.0.2 on 2026-02-13 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL')], max_length=4)),
                ('input_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('misleading', 'Misleading'), ('unknown', 'Unknown')], max_length=11)),
                ('credibility_score', models.IntegerField(help_text='0–100 credibility score.')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('llm_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisrequest')),
            ],
            options={
                'db_table': 'analysis_result',
            },
        ),
        migrations.CreateModel(
            name='SourceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('disputed', 'Disputed'), ('not_found', 'Not Found')], max_length=10)),
                ('match_percentage', models.IntegerField(blank=True, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='analysis.analysisresult')),
            ],
            options={
                'db_table': 'analysis_source_check',
            },
        ),
    ]
