# Generated by Django 6.0.2 on 2026-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='explainable_ai',
            field=models.JSONField(blank=True, default=dict, help_text='Structured JSON explanation from the LLM provider.'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='llm_error',
            field=models.TextField(blank=True, default='', help_text='Error message if LLM call failed.'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='llm_latency_ms',
            field=models.IntegerField(blank=True, help_text='Wall-clock milliseconds the LLM call took.', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='llm_provider',
            field=models.CharField(blank=True, default='ollama', help_text='Which LLM provider produced the explanation.', max_length=50),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='llm_status',
            field=models.CharField(blank=True, default='', help_text='success | error', max_length=20),
        ),
    ]
